######################################################################
# Automatically generated by qmake (1.06c) Sat Feb 28 20:13:05 2004
######################################################################

TEMPLATE = app
DEPENDPATH += src
INCLUDEPATH += . src

# Input
HEADERS += src/altparser.h src/kalternatives.h
SOURCES += src/altparser.cpp src/kalternatives.cpp src/main.cpp
